package InternshinJava;

import java.util.Random;
import java.util.Scanner;



public class RockPaperScissor {
    static int score=0;// static varibale score stores the score of user of each round and incements accordingly if user wins


public static void result(int c, int u){// take two arguent comp and user  and calculate result  based on them
    if(u<0 || u>2){ // if input is  less than zero and greater than 2 than it will return or show Invalid input to user ex -1 or3
        System.out.println("Invalid input");
    }

         else{
          if(u==c){// user and comp input is same than draw (0 0)
            System.out.println("Draw");
        }
        else if(u>c){//user > comp means three cases 2 1 | 2 0 |1 0 -> in which if comp is 0 rock than user lose otherwise wins and this method is applied below
            if(c==0){
                System.out.println("You Lose");
            }
            else {
                System.out.println("You win");
            score++;// scoree incremented by 1
            }
        }
        else{// in this the same goes for the comp when it is greater than user or we can say opposite of above else if
        if(u==0){
            System.out.println("You win");
            score++;//incremented by 1
        }
        else System.out.println("You Lose");

        }


    }


}


    public static void main(String[] args) {
        Random r= new Random();//random number generation

        int i=0;//  for loop
        Scanner sc =new Scanner(System.in);// scanner for input
        System.out.println("Rock paper scissor game ");
        System.out.print("Enter no of rounds you want to play: ");//asking user for input no of rounds , he/she wants to play
        int rounds = sc.nextInt();
        System.out.println("You have to Select [0] for [Rock] , [1] for [Paper] & [2] for [Scissor]");// 0->R 1->P 2->S  [rock 0  beats scissor 2 , scissor 2 beats paper 1 and paper 1 beats rock 0]
        do{
            int comp = r.nextInt(3);// comp stores the random no generated by system
            System.out.print("Enter your option: ");//a sking user for input 0 ,1 or 2
            int user= sc.nextInt();
            result(comp,user);// this method calculates the result of each round between user and comp

           i++; //incrementing i as a round completes
        }while(i<rounds);

        System.out.println("Your score is: "+score);// printing score



    }
}
